---
title: "Profilpunktanalysen Gebiet1"
author: "NA"
date: "09/15/2016"
output: html_document
---

```{r,include=F}
setwd("/home/fabs/Data/paper2_lenny/data_paper2/data2017")
outpath <- "/home/fabs/Data/paper2_lenny/data_paper2/data2017/boden"
source("/home/fabs/Data/paper1_lenny/fabians_and_rossiters_functions.R")
imparameters <- c("Catchment_slope","ChannelNetworkBaseLevel","Channel_Network_Base_Level","Convexity","Longitudinal_Curvature",
                  "Maximum_Height_hr","Normalized_Height","TPI_i0m_o500m","TRI_hr_ws26","Texture",
                  "VerticalDistancetoChannelNetwork","aspect_ws15_hr","bodenbedeckung","crosc_DTM_50m_avg_ws3",
                  "crosc_DTM_50m_avg_ws7","geom_dtm_10m_hyd_fl5_L30","geom_hr_L3_fl1_r.li.simpson_UE_hr_40cells","hoehenstufen",
                  "longc_DTM_50m_avg_ws7","profc_DTM_50m_avg_ws7" ,"slope_DTM_50m_avg_ws3","slope_DTM_50m_avg_ws7","slope_ws15",
                  "slope_ws15_hr")
substratgenesecode <- read.table("substratgenesecode_ohneleerzeichn_2017.csv",header=T, sep=",")
geogenesecode <- read.table("/home/fabs/Data/paper2_lenny/data_paper2/geogenesecode.csv",header=T, sep="\t")
load("/home/fabs/Data/paper2_lenny/data_paper2/geotopodata_chemiereferenz.RData")
modeldata <- modeldata[-c(7:9),]
load("boden_UE_2017.RData")

summary(boden$KLASSE)
Klassen <- levels(boden$KLASSE)
Klassen <- Klassen[!(Klassen %in% c(""))]
Klassen
Typen <- levels(boden$TYP)
Typen <-  Typen[!(Typen %in% c(""))]
Typen
Subtypen <- levels(boden$SUBTYP)
Subtypen <- Subtypen[!(Subtypen %in% c(""))]
Subtypen
summary(boden$SUBTYP)
boden <-boden[boden$KLASSE != "",]
boden <- droplevels(boden)
bodenpunkte <- unique(boden$ID)
levels(boden$KLASSE)
boden$KLASSE <- factor(boden$KLASSE,levels=levels(boden$KLASSE)[c(7,6,1,3,2,5,8,4)])
summary(boden$KLASSE)
levels(boden$TYP)
boden$TYP <- factor(boden$TYP,levels=levels(boden$TYP)[c(4,3,13,8,11,12,1,10,15,6,7,2,16,9,14,5)])
summary(boden$KLASSE)
levels(boden$SUBTYP)
boden$SUBTYP <- factor(boden$SUBTYP,levels=levels(boden$SUBTYP)[c(3,7,6,25,20,18,14,19,16,22,17,24,29,2,28,23,5,1,21,26,
                                                                  12,13,10,27,15,4,8,9,11)])
summary(boden$SUBTYP)
bodenmittopo <- merge(x=boden,y=modeldata,by.x="ID",by.y="ID",all.x=T)
geoklassen <- levels(bodenmittopo$geomorphologie_beschreibung.x)

```
ACHTUNG WAS IST MIT RUTSCHMASSE? 

##BODENKLASSEN
```{r, echo=FALSE}
kl=Klassen[1]
geo=geoklassen[1]
for(geo in geoklassen){
  svg(paste(outpath,"/bodenverteilung ",geo,".svg",sep=""))
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_beschreibung.x %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.6,cex.main=0.9,main=paste("Bodenklassen auf ",geo,sep=""),names=mynames)
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.8,cex.main=0.9,names=typnames,main=paste("Bodentypen auf ",geo,sep=""))
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.8,cex.main=0.9,main=paste("Bodensubtypen auf ",geo,sep=""),names=subtypnames)
  dev.off()
}
```

BEISPIEL PORPHYR
```{r}
outfolder="/home/fabs/Data/paper2_lenny/data_paper2/data2017/silikatboden/"
geo="silikatisches Sedimentgestein"
 svg(paste(outfolder,"bodenverteilung laut geokarte auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_beschreibung.x %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.9,cex.main=0.9,names=mynames,ylim=c(0,10),main=paste("bodenverteilung laut geokarte auf",geo))
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
write.table(as.data.frame(table(geodf$SUBTYP)),file=paste(outfolder,"SF_geo_subtyp.csv",sep=""),sep="\t")
  barplot(table(geodf$TYP),las=2,cex.names=0.9,cex.main=0.9,names=typnames,ylim=c(0,10))
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.9,cex.main=0.9,names=subtypnames,ylim=c(0,5))
  dev.off()
################################################################################################################
svg(paste(outfolder,"bodenverteilung laut kartierer auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_kartiert %in% geo,]

  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.9,cex.main=0.9,names=mynames,ylim=c(0,10))
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.9,cex.main=0.9,names=typnames,ylim=c(0,10))
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.9,cex.main=0.9,names=subtypnames,ylim=c(0,5))
write.table(as.data.frame(table(geodf$SUBTYP)),file=paste(outfolder,"SF_kart_subtyp.csv",sep=""),sep="\t")
  dev.off()
```
GEMISCHTES 
```{r}
outfolder="/home/fabs/Data/paper2_lenny/data_paper2/data2017/gemischtes/"
geo="gemischte Ablagerung"
 svg(paste(outfolder,"bodenverteilung laut geokarte auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_beschreibung.x %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.6,cex.main=0.9,names=mynames)
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.8,cex.main=0.9,names=typnames)
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.8,cex.main=0.9,names=subtypnames)
  dev.off()

 svg(paste(outfolder,"bodenverteilung laut kartierer auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_kartiert %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.6,cex.main=0.9,names=mynames)
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.8,cex.main=0.9,names=typnames)
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.8,cex.main=0.9,names=subtypnames)
  dev.off()
################################################################################################################
geo="gemischte Kegel"
svg(paste(outfolder,"bodenverteilung laut kartierer auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_kartiert %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.6,cex.main=0.9,names=mynames)
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.8,cex.main=0.9,names=typnames)
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.8,cex.main=0.9,names=subtypnames)
  dev.off()

geo="gemischte Kegel"
svg(paste(outfolder,"bodenverteilung laut geokarte auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_beschreibung.x %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.6,cex.main=0.9,names=mynames)
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.8,cex.main=0.9,names=typnames)
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.8,cex.main=0.9,names=subtypnames)
  dev.off()
```
HANGSCHUTT

```{r}
################################################################################################################
outfolder="/home/fabs/Data/paper2_lenny/data_paper2/data2017/hangschutt/"
geo="Hangschutt"
svg(paste(outfolder,"bodenverteilung laut Kartierer auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_kartiert %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.9,cex.main=0.9,names=mynames,ylim=c(0,80))
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.9,cex.main=0.9,names=typnames,ylim=c(0,35))
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.9,cex.main=0.9,names=subtypnames,ylim=c(0,30))
write.table(as.data.frame(table(geodf$SUBTYP)),file=paste(outfolder,"HS_geo_subtyp.csv",sep=""),sep="\t")
  dev.off()
svg(paste(outfolder,"bodenverteilung laut geokarte auf",geo,".svg",sep=""),bg="transparent")
  par(mfcol=c(3,1))
  geodf <- bodenmittopo[bodenmittopo$geomorphologie_beschreibung.x %in% geo,]
  par(mar=c(7,3,1,1))
   mynames=c(paste("TERRESTRISCHE"," ROHBÖDEN",sep="\n") ,  "TERRESTRISCHE \n HUMUSBÖDEN", "BRAUNERDEN" , "PODSOLE","KALKLEHME"  ,     "SUBSTRATBÖDEN" ,           "UMGELAGERTE\nBÖDEN"   ,     "PSEUDOGLEYE"   )
  barplot(table(geodf$KLASSE),las=2,cex.names=0.9,cex.main=0.9,names=mynames,ylim=c(0,80))
  par(mar=c(9,4,1,1))
  typnames=c("Grobmaterial-\nRohboden", "Feinmaterial-\nRohboden", "Rendzina","Kalklehm-\nRendzina", "Pararendzina","Ranker",
             "Braunerde","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\n rezent","Farb-\nSubstratboden",
             "Textur-\nSubstratboden","Kolluvisol","Rigolboden","Haftnässe-\nPseudogley") 
  barplot(table(geodf$TYP),las=2,cex.names=0.9,cex.main=0.9,names=typnames,ylim=c(0,35))
  par(mar=c(11,4,1,1))
  subtypnames <- c("Carbonatfreier\nGrobmaterial-Rohboden","Carbonathaltiger\nGrobmaterial-Rohboden","Carbonathaltiger\nFeinmaterial-Rohboden","Rendzina","Mull-Rendzina","Moder-Rendzina","Kalklehm-Rendzina","Mull-\nKalklehm-Rendzina","Moder-\nKalklehm-Rendzina","Pararendzina","Moder-\nPararendzina","Ranker","Typischer Ranker","Carbonatfreier\nFels-Auflagehumusboden",
                   "Typische Braunerde","Podsolige\nBraunerde","Carbonathaltige\nBraunerde","Braunerde -\ntonig","Parabraunerde","Semipodsol","Kalkbraunlehm","Kalklehme -\nrezent", "Farb-\nSubstratboden","Textur-\nSubstratboden","Kolluvisol","Carbonatfreier\nKolluvisol","carbonathaltiger\nKolluvisol" , "Carbonathaltiger\nRigolboden","Haftnässe-\nPseudogley")
  barplot(table(geodf$SUBTYP),las=2,cex.names=0.9,cex.main=0.9,names=subtypnames,ylim=c(0,30))
write.table(as.data.frame(table(geodf$SUBTYP)),file=paste(outfolder,"HS_kart_subtyp.csv",sep=""),sep="\t")
  dev.off()
```


